# -*- coding: utf-8 -*-
"""earthquake alert.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1fZsq-I-55RqiOXkAG5pCVEX4Gadtr4eF
"""

import requests
import xml.etree.ElementTree as ET
import time
from gtts import gTTS
import streamlit as st

st.title ("地震速報アプリ")
st.write("ここに地震情報を表示します")

# 気象庁 地震速報フィードURL
JMA_EARTHQUAKE_FEED_URL = "https://www.data.jma.go.jp/developer/xml/feed/eqvol.xml"

# 直前に取得した速報タイトル（重複防止用）
last_earthquake_title = ""

# 行動指示辞書
actions = {
    1: "安全を確保してください。テーブルや丈夫な物の下に隠れてください。",
    2: "揺れが収まったら、避難ルートを確認し、落下物に注意してください。",
    3: "必要に応じて避難を開始してください。周囲の安全を確認してください。また、ガス栓を締め、必要であればブレーカーを落としてください。",
}

# 現在の行動ステップ
current_step = 1

# ボタンのクリックで次のステップに進む
def next_step():
    global current_step
    if current_step < 3:
        current_step += 1
    else:
        print("全ての行動指示が完了しました。")

    # 音声で行動指示を読み上げる
    action_message = actions.get(current_step, "行動指示がありません。")
    tts = gTTS(text=action_message, lang='ja')
    tts.save("action.mp3")

    # 音声再生
    st.audio("action.mp3", autoplay=True)
    # 行動指示を表示
    st.write(action_message)

# 地震速報を取得する関数
def fetch_latest_earthquake_info():
    try:
        response = requests.get(JMA_EARTHQUAKE_FEED_URL)
        response.raise_for_status()
        root = ET.fromstring(response.content)
        first_entry = root.find('channel/item')
        title =

